name: Publish Docker image

on:
  push:
    tags:
      - 'v*'  # El trigger se activa solo cuando el tag comienza con "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image-name:${TAG_NAME} .

      - name: Push the Docker image to Docker Hub
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:${TAG_NAME}
